# Generated by Django 4.1.7 on 2023-04-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotecaVirtual', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tapa',
            field=models.ImageField(blank=True, null=True, upload_to='tapas'),
        ),
    ]
